# Generated by Django 5.2.10 on 2026-01-18 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_card', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('defender_card', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FINISHED', 'Finished')], default='PENDING', max_length=10)),
                ('rule', models.CharField(blank=True, choices=[('BIGGER_WINS', 'Bigger wins'), ('SMALLER_WINS', 'Smaller wins')], max_length=20, null=True)),
                ('winner', models.CharField(blank=True, choices=[('ATTACKER', 'Attacker'), ('DEFENDER', 'Defender'), ('DRAW', 'Draw')], max_length=10, null=True)),
                ('attacker_delta', models.IntegerField(default=0)),
                ('defender_delta', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_attacked', to=settings.AUTH_USER_MODEL)),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_defended', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
